name: CI/CD Pipeline

# Run workflow on every push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4   # make sure v4 is used
        with:
          context: .
          push: true
          tags: ashish0219/californiahousingprices:latest
